CONFIG_SPI=y
CONFIG_ZMK_POINTING=y
CONFIG_PAW3395=y

# Wheel encoder (on the NFC pads, see ezeco_mouse.overlay).
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
